### ISSUE TITLE
PVP Bug

### ISSUE THREAD

**Issue by christheboss894** [PeachesMLG/IridiumSkyblock#23]
If you are both in the same island, then even in different worlds, you cannot damage eachother

**Comment by PeachesMLG** [comment]
its designed to do that so i wouldnt call it a bug. If you dont want it to do that ill add an option in the config to disable it

**Comment by christheboss894** [comment]
i understand its meant to do that on the skyblock world, but it shouldnt do that on other worlds, you need to add a check for if the world is skyblock, pvp = off, if world is not skyblock, pvp = on

**Comment by Jowcey** [comment]
@PeachesMLG just going to piggyback on this feature request, what about adding an ArrayList that contains a list of worlds that a user can define in say "worlds.yml" and only the worlds in that list will be recognised as skyblock worlds? :)

**Comment by PeachesMLG** [comment]
I was gona do the opposite actually xD and just have a disabledworlds
